version: "3.8"
services:
  mlflow:
    build:
      context: mlflow/.
    ports:
      - 1234:1234
    working_dir: /work
    command: poetry run mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root artifacts/ --host 0.0.0.0 --port 1234
    volumes:
      - ".:/work"
  fastapi:
    build:
      context: fastapi/.
    ports:
      - 5000:5000
    working_dir: /work
    command: poetry run mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root artifacts/ --host 0.0.0.0 --port 5000
    volumes:
      - ".:/work"