version: "3.8"
services:
  mlflow:
    build:
      context: .
    ports:
      - ${MLFLOW_PORT}:${MLFLOW_PORT}
    working_dir: /work
    command: poetry run mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root artifacts/ --host 0.0.0.0 --port ${MLFLOW_PORT}
    volumes:
      - ".:/work"
      - "mlflow-volume:/work/.cache/"
  fastapi:
    build:
      context: .
    ports:
      - ${FASTAPI_PORT}:${FASTAPI_PORT}
    working_dir: /work
    command: poetry run uvicorn prediction_service.app:app --host 0.0.0.0 --port ${FASTAPI_PORT}
    volumes:
      - ".:/work"
      - "fastapi-volume:/work/.cache/"
volumes:
  mlflow-volume:
    name: mlflow-volume
  fastapi-volume:
    name: fastapi-volume