stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - src/prepare.py
    params:
    - prepare.categories
    outs:
    - data/prepared
  featurize:
    cmd: python3 src/featurize.py data/prepared data/features
    deps:
    - data/prepared
    - src/featurize.py
    outs:
    - data/features
  train:
    cmd: python src/train.py --config=params.yaml
    deps:
    - data/features
    - src/train.py
    params:
    - train.alpha
    outs:
    - models/model.pkl
  log_production_model:
    cmd: python src/log_production_model.py --config=params.yaml
    deps:
    - src/log_production_model.py
    outs:
    - prediction_service/model/model.joblib
