prepare:
    categories:
        - comp.graphics
        - rec.sport.baseball
    data_preprocessed: data/features
train:
    alpha: 15
    outputed_model: models/model.pkl
mlflow_config:
  artifacts_dir: artifacts
  experiment_name: Naive_B
  run_name: mlops
  registered_model_name: MultinomialNB
  remote_server_uri: http://mlflow:5000
webapp_model_dir: prediction_service/model/model.joblib
